"""Utilities for robustly extracting and parsing JSON from LLM outputs."""

import json
import re
from typing import Any, Dict


def extract_json(text: str) -> Dict[str, Any]:
    """Extract and parse a JSON dictionary from raw LLM completion text.

    Handles:
    - Markdown code fences (e.g. ```json ... ``` or ``` ... ```)
    - Surrounding conversational commentary
    - Leading/trailing whitespace

    Args:
        text: Raw text generated by an LLM.

    Returns:
        Parsed JSON dictionary.

    Raises:
        ValueError: If no valid JSON dictionary can be found or parsed.
    """
    if not text or not text.strip():
        raise ValueError("Cannot extract JSON from empty text.")

    cleaned = text.strip()

    # 1. Try stripping markdown code fences
    fence_pattern = r"^```(?:json)?\s*\n?(.*?)\n?```$"
    match = re.search(fence_pattern, cleaned, flags=re.DOTALL)
    if match:
        cleaned = match.group(1).strip()

    # 2. Try direct JSON parsing
    try:
        data = json.loads(cleaned)
        if isinstance(data, dict):
            return data
    except json.JSONDecodeError:
        pass

    # 3. Extract outermost curly braces { ... }
    brace_match = re.search(r"(\{.*\})", cleaned, flags=re.DOTALL)
    if brace_match:
        json_candidate = brace_match.group(1).strip()
        try:
            data = json.loads(json_candidate)
            if isinstance(data, dict):
                return data
        except json.JSONDecodeError:
            pass

        # 4. Handle common trailing comma issues before closing braces
        sanitized = re.sub(r",\s*([\}\]])", r"\1", json_candidate)
        try:
            data = json.loads(sanitized)
            if isinstance(data, dict):
                return data
        except json.JSONDecodeError:
            pass

    raise ValueError(f"Failed to extract valid JSON dictionary from LLM output:\n{text[:300]}...")
